### ISSUE TITLE
Create a text formatting system

### ISSUE THREAD

**Issue by Ruin0x11** [ElonaFoobar/ElonaFoobar#317]
# Details
The current system of using inline text transformers inside `txt` isn't healthy for true internationalization and for interfacing with Lua. There should be a general text formatting format. 

Here is an example of adding a localization config for a mod, and using specified variables inside it.

In `mods/core/locale/en.toml`:
```toml
[text]
steal="<name $1> steal<s $1> from \<Legendary\> <name $2>."
```

In `mods/core/init.lua`:
```lua
Elona.GUI.txt("core.text.steal", chara, target)
```

Or, to make it more clear what the arguments are:

```toml
[text]
steal="{ $cc, $tc } -> <name $cc> steal<s $cc> from \<Legendary\> <name $tc>."
```

The [Fluent](https://github.com/projectfluent/fluent-rs) project takes this approach. It also has built-in functions.

All localizations have to have the same number of arguments, otherwise positioning will differ between languages. Static analysis can be used to detect user errors where a different number of arguments was passed to `Elona.GUI.txt`, or the definitions in `locale` don't all have the same number of arguments.
